In [53]:
import pandas as pd
import pyodbc
conn = pyodbc.connect(r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\BRIJ BHUSHAN\Downloads\CDRData\CDR_Data.mdb;')
cursor = conn.cursor()

'''cnxn   = pyodbc.connect(...)
cursor = cnxn.cursor()'''

for row in cursor.tables():
    print (row.table_name)

MSysAccessObjects
MSysAccessXML
MSysACEs
MSysNameMap
MSysNavPaneGroupCategories
MSysNavPaneGroups
MSysNavPaneGroupToObjects
MSysNavPaneObjectIDs
MSysObjects
MSysQueries
MSysRelationships
customerCalls
customerInformation
incomming
model
model-OffPeak
model-Peak
Paste Errors
phoneNumberData
phoneNumberType
Table1
timeData
timePlans
customerCalls Query
customerCalls Query1
customerCalls Query2
customerInformation Query
Intl
model Query
model Query1
qryAllOutputs4Weeks
qryCallInfo4Weeks
qryCallSummary4Weeksv2
qryCodeCounts
qryGetLocalCodes
qryHighRisk-CallSummary4Weeks2
qryLowRisk-CallSummary4Weeks2
qryModels
qryPeriodIncomming-4Weeks
qryTimeData
qryTimeDataChrt
qryTimePlans


In [54]:
SQL_Query = pd.read_sql_query(
'''SELECT * FROM customerInformation''', conn)

df = pd.DataFrame(SQL_Query, columns=['customerPhoneNumber','incomingCalls', 'modelID', 'dataType'])
df

customerPhoneNumber  incomingCalls  modelID  dataType
0             0296393418            250        1         1
1             0141382566            239        1         2
2             0187219904            254        1         3
3             0144631092            255        1         4
4             0159361948            255        1         0
...                  ...            ...      ...       ...
1043          0138869101            244       20         1
1044          0284124565            250       20         2
1045          0147115510            249       20         3
1046          0177249622            253       20         4
1047          0125595988            251       20         0

[1048 rows x 4 columns]

In [55]:
SQL_Query = pd.read_sql_query(
str.format('''SELECT top {0} * FROM customerInformation''', 10), conn)

df = pd.DataFrame(SQL_Query, columns=['customerPhoneNumber','incomingCalls', 'modelID', 'dataType'])
df

customerPhoneNumber  incomingCalls  modelID  dataType
0          0296393418            250        1         1
1          0141382566            239        1         2
2          0187219904            254        1         3
3          0144631092            255        1         4
4          0159361948            255        1         0
5          0172146676            256        1         1
6          0114946582            248        1         2
7          0168966959            255        1         3
8          0134913794            240        1         4
9          0172531410            251        1         0

In [56]:
SQL_Query = pd.read_sql_query(
    '''Select * from phoneNumberType
    ''',conn)

df = pd.DataFrame(SQL_Query)
df

typeID  typeName
0       1      Free
1       2     Local
2       3  National
3       4      Intl
4       5       PRS
5       6    Mobile

In [57]:
SQL_Query = pd.read_sql_query(
    '''Select top 10  * from ((customerCalls cusCall
        INNER join customerinformation cusInfo on 
        cusCall.customerphoneNumber = cusInfo.customerphoneNumber)
        INNER JOIN model mdl on mdl.modelID = cusInfo.modelID)
    ''',conn)

df = pd.DataFrame(SQL_Query)
df.columns

Index(['callID', 'customerPhoneNumber', 'startDate', 'endDate', 'callStart',
       'callEnd', 'phoneNumber', 'callType', 'callCost', 'customerPhoneNumber',
       'incomingCalls', 'modelID', 'dataType', 'modelID', 'modelName',
       'numAccounts', 'callsMean', 'callsStdDev', 'startDate', 'endDate',
       'offPeakStart', 'offPeakEnd', 'numIncommingMean', 'numIncommingStdDev',
       'fraudulent', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat', 'sun',
       'meanNumOutLocal', 'stdDevNumOutLocal', 'meanNumOutFree',
       'stdDevNumOutFree', 'meanNumOutNational', 'stdDevNumOutNational',
       'meanNumOutIntl', 'stdDevNumOutIntl', 'meanNumOutPRS',
       'stdDevNumOutPRS', 'meanNumOutMobile', 'stdDevNumOutMobile',
       'meanPhoneLines', 'stdDevPhoneLines'],
      dtype='object')

In [58]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\BRIJ BHUSHAN\Downloads\CDRData\CDR_Data.mdb;')
SQL_Query = pd.read_sql_query(
    '''SELECT  
        cusCall.callID, 
        cusCall.customerPhoneNumber, 
        cusCall.startDate,
        cusCall.endDate,
        cusCall.callStart,
        cusCall.callEnd,
        cusCall.callType,
        cusCall.callCost,
        cusInfo.incomingCalls,
        cusInfo.modelID,
        mdl.modelName,
        mdl.fraudulent
        FROM ((customerCalls cusCall
        INNER JOIN customerinformation cusInfo ON 
        cusCall.customerphoneNumber = cusInfo.customerphoneNumber)
        INNER JOIN model mdl ON mdl.modelID = cusInfo.modelID)
    ''', conn)

df_data = pd.DataFrame(SQL_Query)
df_data

callID customerPhoneNumber  startDate    endDate  \
0              1          0296393418 2013-01-02 2013-01-02   
1              2          0296393418 2013-10-02 2013-10-02   
2              3          0296393418 2013-01-20 2013-01-20   
3              4          0296393418 2013-01-21 2013-01-21   
4              5          0296393418 2013-02-03 2013-02-03   
...          ...                 ...        ...        ...   
1109339  1109340          0125595988 2013-06-02 2013-06-02   
1109340  1109341          0125595988 2013-01-14 2013-01-14   
1109341  1109342          0125595988 2013-02-24 2013-02-24   
1109342  1109343          0125595988 2013-01-13 2013-01-13   
1109343  1109344          0125595988 2013-01-19 2013-01-19   

                  callStart             callEnd  callType    callCost  \
0       1899-12-30 06:25:00 1899-12-30 06:28:00  National   15.113445   
1       1899-12-30 10:00:00 1899-12-30 10:05:00  National   23.026891   
2       1899-12-30 16:45:00 1899-12-30 17:12:00     Local   27.176660   
3       1899-12-30 20:35:00 1899-12-30 20:58:00     Local   23.828167   
4       1899-12-30 21:20:00 1899-12-30 21:51:00     Local   31.088230   
...                     ...                 ...       ...         ...   
1109339 1899-12-30 01:10:00 1899-12-30 01:18:00    Mobile  134.064582   
1109340 1899-12-30 10:35:00 1899-12-30 10:47:00  National   48.032496   
1109341 1899-12-30 12:45:00 1899-12-30 12:51:00       PRS  312.290070   
1109342 1899-12-30 13:30:00 1899-12-30 13:30:00       PRS   41.802818   
1109343 1899-12-30 12:40:00 1899-12-30 12:58:00       PRS  945.321113   

         incomingCalls  modelID                        modelName  fraudulent  
0                  250        1                   Normal Average       False  
1                  250        1                   Normal Average       False  
2                  250        1                   Normal Average       False  
3                  250        1                   Normal Average       False  
4                  250        1                   Normal Average       False  
...                ...      ...                              ...         ...  
1109339            251       20  Fraud Home Call Sell PRS Hidden        True  
1109340            251       20  Fraud Home Call Sell PRS Hidden        True  
1109341            251       20  Fraud Home Call Sell PRS Hidden        True  
1109342            251       20  Fraud Home Call Sell PRS Hidden        True  
1109343            251       20  Fraud Home Call Sell PRS Hidden        True  

[1109344 rows x 12 columns]

In [60]:
df_data = df_data.assign(startDay = df_data['startDate'].dt.day_name())
df_data = df_data.assign(endDay = df_data['endDate'].dt.day_name())

In [61]:
from sklearn.model_selection import train_test_split
df_data_X = df_data[["callID", "callStart", "callEnd", "startDay", "endDay", "callType", "callCost"]]
df_data_y = df_data["fraudulent"].astype(int)
X_train_data_set, X_test_data_set, y_train_data_set, y_test_data_set = train_test_split(df_data_X, df_data_y, test_size=0.33, random_state=9)

In [62]:
df_data_y.head()

0    0
1    0
2    0
3    0
4    0
Name: fraudulent, dtype: int32

In [63]:
X_train_data_set.head()

callID           callStart             callEnd   startDay  \
320882    320883 1899-12-30 19:05:00 1899-12-30 19:22:00  Wednesday   
578831    578832 1899-12-30 19:25:00 1899-12-30 19:42:00   Saturday   
1100923  1100924 1899-12-30 19:30:00 1899-12-30 19:38:00  Wednesday   
871404    871405 1899-12-30 19:55:00 1899-12-30 20:24:00     Monday   
860338    860339 1899-12-30 14:25:00 1899-12-30 14:35:00     Monday   

            endDay  callType    callCost  
320882   Wednesday  National   71.999527  
578831    Saturday  National   70.958992  
1100923  Wednesday    Mobile  126.047481  
871404      Monday  National  118.117257  
860338      Monday    Mobile  164.157817

In [64]:
print("-----------------Description--------------------\n")
print(X_train_data_set.describe())
print("\n\n-----------------Information--------------------\n")
print(X_train_data_set.info())

-----------------Description--------------------

             callID       callCost
count  7.432600e+05  743260.000000
mean   5.549190e+05     103.020810
std    3.201184e+05     339.921666
min    1.000000e+00       0.000000
25%    2.778148e+05      21.740348
50%    5.550045e+05      49.206513
75%    8.320105e+05      97.102820
max    1.109344e+06    9084.506862


-----------------Information--------------------

<class 'pandas.core.frame.DataFrame'>
Int64Index: 743260 entries, 320882 to 516478
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   callID     743260 non-null  int64         
 1   callStart  743260 non-null  datetime64[ns]
 2   callEnd    743260 non-null  datetime64[ns]
 3   startDay   743260 non-null  object        
 4   endDay     743260 non-null  object        
 5   callType   743260 non-null  object        
 6   callCost   743260 non-null  float64       
dtypes: datetime64[ns](2), float64(1

In [65]:
SQL_Query = pd.read_sql_query(
str.format('''SELECT top {0} * FROM Intl''', 10), conn)

df = pd.DataFrame(SQL_Query)
df

Call Type  Field1
0          4   09001
1          4   09002
2          4  090030
3          4  090031
4          4  090032
5          4  090033
6          4  090034
7          4  090035
8          4  090036
9          4  090037

In [66]:
print("-----------------Description--------------------\n")
print(X_train_data_set.describe())
print("\n\n-----------------Information--------------------\n")
print(X_train_data_set.info())
X_train_data_set.head()

-----------------Description--------------------

             callID       callCost
count  7.432600e+05  743260.000000
mean   5.549190e+05     103.020810
std    3.201184e+05     339.921666
min    1.000000e+00       0.000000
25%    2.778148e+05      21.740348
50%    5.550045e+05      49.206513
75%    8.320105e+05      97.102820
max    1.109344e+06    9084.506862


-----------------Information--------------------

<class 'pandas.core.frame.DataFrame'>
Int64Index: 743260 entries, 320882 to 516478
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   callID     743260 non-null  int64         
 1   callStart  743260 non-null  datetime64[ns]
 2   callEnd    743260 non-null  datetime64[ns]
 3   startDay   743260 non-null  object        
 4   endDay     743260 non-null  object        
 5   callType   743260 non-null  object        
 6   callCost   743260 non-null  float64       
dtypes: datetime64[ns](2), float64(1

callID           callStart             callEnd   startDay  \
320882    320883 1899-12-30 19:05:00 1899-12-30 19:22:00  Wednesday   
578831    578832 1899-12-30 19:25:00 1899-12-30 19:42:00   Saturday   
1100923  1100924 1899-12-30 19:30:00 1899-12-30 19:38:00  Wednesday   
871404    871405 1899-12-30 19:55:00 1899-12-30 20:24:00     Monday   
860338    860339 1899-12-30 14:25:00 1899-12-30 14:35:00     Monday   

            endDay  callType    callCost  
320882   Wednesday  National   71.999527  
578831    Saturday  National   70.958992  
1100923  Wednesday    Mobile  126.047481  
871404      Monday  National  118.117257  
860338      Monday    Mobile  164.157817

In [67]:
SQL_Query = pd.read_sql_query(
str.format('''SELECT top {0} * FROM Intl''', 10), conn)

df = pd.DataFrame(SQL_Query)
df

Call Type  Field1
0          4   09001
1          4   09002
2          4  090030
3          4  090031
4          4  090032
5          4  090033
6          4  090034
7          4  090035
8          4  090036
9          4  090037

In [68]:
print("-----------------Description--------------------\n")
print(X_train_data_set.describe())
print("\n\n-----------------Information--------------------\n")
print(X_train_data_set.info())
X_train_data_set.head()

-----------------Description--------------------

             callID       callCost
count  7.432600e+05  743260.000000
mean   5.549190e+05     103.020810
std    3.201184e+05     339.921666
min    1.000000e+00       0.000000
25%    2.778148e+05      21.740348
50%    5.550045e+05      49.206513
75%    8.320105e+05      97.102820
max    1.109344e+06    9084.506862


-----------------Information--------------------

<class 'pandas.core.frame.DataFrame'>
Int64Index: 743260 entries, 320882 to 516478
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   callID     743260 non-null  int64         
 1   callStart  743260 non-null  datetime64[ns]
 2   callEnd    743260 non-null  datetime64[ns]
 3   startDay   743260 non-null  object        
 4   endDay     743260 non-null  object        
 5   callType   743260 non-null  object        
 6   callCost   743260 non-null  float64       
dtypes: datetime64[ns](2), float64(1

callID           callStart             callEnd   startDay  \
320882    320883 1899-12-30 19:05:00 1899-12-30 19:22:00  Wednesday   
578831    578832 1899-12-30 19:25:00 1899-12-30 19:42:00   Saturday   
1100923  1100924 1899-12-30 19:30:00 1899-12-30 19:38:00  Wednesday   
871404    871405 1899-12-30 19:55:00 1899-12-30 20:24:00     Monday   
860338    860339 1899-12-30 14:25:00 1899-12-30 14:35:00     Monday   

            endDay  callType    callCost  
320882   Wednesday  National   71.999527  
578831    Saturday  National   70.958992  
1100923  Wednesday    Mobile  126.047481  
871404      Monday  National  118.117257  
860338      Monday    Mobile  164.157817

In [69]:
import datetime 
import calendar
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

class CallDurationAttribute(BaseEstimator, TransformerMixin):

    def __init__(self, includeSeconds=False):
        self.includeSeconds = includeSeconds
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        callDuration = pd.DataFrame(X[:,2] - X[:,1])
        
      
        duration_hours = callDuration.apply(lambda h : h[0].components[1], axis=1)
        duration_minutes = callDuration.apply(lambda m : m[0].components[2], axis=1)
        
        
        
        
        if self.includeSeconds:  
            duration_seconds = callDuration.apply(lambda s : s[0].components[3], axis=1)
            
            return np.c_[X, duration_hours, duration_minutes, duration_seconds]
        else:
            return np.c_[X, duration_hours, duration_minutes]
        

In [70]:
X_train_data_set.head()

callID           callStart             callEnd   startDay  \
320882    320883 1899-12-30 19:05:00 1899-12-30 19:22:00  Wednesday   
578831    578832 1899-12-30 19:25:00 1899-12-30 19:42:00   Saturday   
1100923  1100924 1899-12-30 19:30:00 1899-12-30 19:38:00  Wednesday   
871404    871405 1899-12-30 19:55:00 1899-12-30 20:24:00     Monday   
860338    860339 1899-12-30 14:25:00 1899-12-30 14:35:00     Monday   

            endDay  callType    callCost  
320882   Wednesday  National   71.999527  
578831    Saturday  National   70.958992  
1100923  Wednesday    Mobile  126.047481  
871404      Monday  National  118.117257  
860338      Monday    Mobile  164.157817

In [71]:
class CallDayAttribute(BaseEstimator, TransformerMixin):

    def __init__(self):
        pass
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        callDay = pd.DataFrame(X[:,0])
        
        call_Day =callDay[0].dt.day_name()
      
        return np.c_[X, call_Day]

In [72]:
class AttributeSelector(BaseEstimator, TransformerMixin):

    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):  
        return X[self.attribute_names].values
    

In [73]:
class DropDataFrameColumns(BaseEstimator, TransformerMixin):

    def __init__(self, drop=True):
        self.drop = drop
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        
        result = pd.DataFrame(X[:,3:])
        return np.c_[result]
        

In [74]:
X_train_data_set.head()

callID           callStart             callEnd   startDay  \
320882    320883 1899-12-30 19:05:00 1899-12-30 19:22:00  Wednesday   
578831    578832 1899-12-30 19:25:00 1899-12-30 19:42:00   Saturday   
1100923  1100924 1899-12-30 19:30:00 1899-12-30 19:38:00  Wednesday   
871404    871405 1899-12-30 19:55:00 1899-12-30 20:24:00     Monday   
860338    860339 1899-12-30 14:25:00 1899-12-30 14:35:00     Monday   

            endDay  callType    callCost  
320882   Wednesday  National   71.999527  
578831    Saturday  National   70.958992  
1100923  Wednesday    Mobile  126.047481  
871404      Monday  National  118.117257  
860338      Monday    Mobile  164.157817

In [75]:
from sklearn.preprocessing import LabelBinarizer

class CustomLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, sparse_output=False):
        self.sparse_output = sparse_output
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = LabelBinarizer(sparse_output=self.sparse_output)
        return enc.fit_transform(X)

In [76]:
from sklearn.preprocessing import MultiLabelBinarizer

class CustomMultiLabelBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, sparse_output=False):
        self.sparse_output = sparse_output
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        enc = MultiLabelBinarizer(sparse_output=self.sparse_output)
        return enc.fit_transform(X)

In [77]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelBinarizer
from sklearn.compose import ColumnTransformer

duration_attributes = ["callID", "callStart", "callEnd"]
callday_attributes = ["startDate"]
cat_attributes = ["callType"]
multilabel_cat_attributes = ["startDay"]

duration_pipeline = Pipeline(
    [
        ('selector', AttributeSelector(duration_attributes)),
        ('attr_add', CallDurationAttribute())
    ]
)

cat_pipeline = Pipeline(
    [
        ('selector', AttributeSelector(cat_attributes)),
        ('label_binarizer', CustomLabelBinarizer())
    ]
)

multilable_cat_pipeline = Pipeline(
    [
        ('selector', AttributeSelector(multilabel_cat_attributes)),
        ('label_binarizer', CustomLabelBinarizer())
    ]
)


In [78]:
from sklearn.pipeline import FeatureUnion
cdr_pipeline = FeatureUnion(transformer_list =[
    ("duration_pipeline", duration_pipeline),
    ("cat_pipeline", cat_pipeline),
    ("multilable_cat_pipeline",multilable_cat_pipeline)
])

df_data_prepared = cdr_pipeline.transform(X_train_data_set)
df_data_prepared = df_data_prepared[:,3:]
df_data_prepared

array([[0, 17, 0, ..., 0, 0, 1],
       [0, 17, 0, ..., 0, 0, 0],
       [0, 8, 0, ..., 0, 0, 1],
       ...,
       [0, 27, 0, ..., 0, 0, 0],
       [0, 11, 0, ..., 0, 0, 0],
       [0, 12, 0, ..., 0, 0, 0]], dtype=object)

In [79]:
v= pd.DataFrame(df_data_prepared)
v.head(1000)

0   1  2  3  4  5  6  7  8  9  10 11 12 13 14
0    0  17  0  0  0  0  1  0  0  0  0  0  0  0  1
1    0  17  0  0  0  0  1  0  0  0  1  0  0  0  0
2    0   8  0  0  0  1  0  0  0  0  0  0  0  0  1
3    0  29  0  0  0  0  1  0  0  1  0  0  0  0  0
4    0  10  0  0  0  1  0  0  0  1  0  0  0  0  0
..  ..  .. .. .. .. .. .. .. .. .. .. .. .. .. ..
995  0   5  0  0  0  1  0  0  0  0  0  1  0  0  0
996  0   5  0  0  0  0  1  0  0  0  0  0  1  0  0
997  0  21  0  0  1  0  0  0  0  0  0  0  0  0  1
998  0   6  0  1  0  0  0  0  0  0  0  1  0  0  0
999  0  17  0  1  0  0  0  0  0  0  0  1  0  0  0

[1000 rows x 15 columns]

In [80]:
from sklearn.linear_model import SGDClassifier
sgl_clf = SGDClassifier(random_state=42)
sgl_clf.fit(df_data_prepared, y_train_data_set)

SGDClassifier(random_state=42)

In [81]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgl_clf, df_data_prepared, y_train_data_set, cv=10, scoring='accuracy')

array([0.99695934, 0.99709388, 0.9971477 , 0.99718806, 0.99720152,
       0.99693243, 0.99691898, 0.99725533, 0.99724188, 0.99613863])

In [82]:
df_test_data_prepared = cdr_pipeline.transform(X_test_data_set)
df_test_data_prepared = df_test_data_prepared[:,3:]
df_test_data_prepared

array([[0, 2, 0, ..., 0, 1, 0],
       [0, 25, 0, ..., 0, 0, 0],
       [0, 28, 0, ..., 0, 0, 0],
       ...,
       [0, 6, 0, ..., 0, 0, 0],
       [0, 9, 0, ..., 0, 0, 0],
       [0, 23, 0, ..., 1, 0, 0]], dtype=object)

In [83]:
y_test_data_set

838067    0
598387    0
727548    0
739277    0
919709    0
         ..
172014    0
101895    0
989481    0
999785    0
371544    0
Name: fraudulent, Length: 366084, dtype: int32

In [84]:
test_predict = sgl_clf.predict(df_test_data_prepared)

In [85]:
test_predict

array([0, 0, 0, ..., 0, 0, 0])

In [86]:
sgl_clf.score(df_test_data_prepared, y_test_data_set)

0.9968859605992068

In [87]:
from sklearn.metrics import f1_score
score = f1_score(test_predict, y_test_data_set)

In [88]:
score

0.9181622397702799

In [89]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
print(f1_score(y_test_data_set, test_predict, average="macro"))
print(precision_score(y_test_data_set, test_predict, average="macro"))
print(recall_score(y_test_data_set, test_predict, average="macro"))  
print("\n-----------------------------------------------\n")
print(f1_score(y_test_data_set, test_predict))
print(precision_score(y_test_data_set, test_predict))
print(recall_score(y_test_data_set, test_predict)) 
print(confusion_matrix(y_test_data_set, test_predict))
print(classification_report(y_test_data_set, test_predict))

0.9582875110813729
0.9865057219067437
0.9332789135651142

-----------------------------------------------

0.9181622397702799
0.9757400061031432
0.8670010845986985
[[358549    159]
 [   981   6395]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    358708
           1       0.98      0.87      0.92      7376

    accuracy                           1.00    366084
   macro avg       0.99      0.93      0.96    366084
weighted avg       1.00      1.00      1.00    366084



In [90]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test_data_set, sgl_clf.decision_function(df_test_data_prepared), average="macro")

0.964550662693167

Implementation of DecisionTreeRegression Model 

In [38]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
dtr = DecisionTreeRegressor()

dtr.fit(df_data_prepared,y_train_data_set)


print(dtr.score(df_test_data_prepared,y_test_data_set))

0.8709087222993359


In [92]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
clf = DecisionTreeClassifier()
clf.fit(df_data_prepared,y_train_data_set)
clf.score(df_test_data_prepared,y_test_data_set)

0.9972465335824565

In [93]:
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,32,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),
    'splitter' : ['best', 'random']
    
}

In [97]:
grid_search = GridSearchCV(estimator=clf,
                     param_grid=grid_param,
                     cv=5,
                    n_jobs =3)

In [ ]:
grid_search.fit(df_data_prepared,y_train_data_set)

In [ ]:
best_parameters = grid_search.best_params_
print(best_parameters)

In [ ]:
grid_search.best_score_

In [ ]:
clf = DecisionTreeClassifier(criterion = 'entropy', max_depth =24, min_samples_leaf= 1, min_samples_split= 2, splitter ='random')
clf.fit(df_data_prepared,y_train_data_se)

In [ ]:
clf.score(x_test,y_test)